#!/usr/bin/env python

# Run this before you deploy it on replicate
import os
import sys
import torch
from huggingface_hub import snapshot_download
from models import VisionEncoder, TextModel
sys.path.extend(['/moondream'])

# append project directory to path so predict.py can be imported
sys.path.append('.')
from predict import MODEL_NAME, MODEL_CACHE

# Make cache folders
if not os.path.exists(MODEL_CACHE):
    os.makedirs(MODEL_CACHE)

snapshot_download(MODEL_NAME, local_dir=MODEL_CACHE)
    
vision_encoder = VisionEncoder(MODEL_CACHE)
text_model = TextModel(MODEL_CACHE)

vision_encoder.save_pretrained(MODEL_CACHE)
text_model.save_pretrained(MODEL_CACHE)